# Generated by Django 5.1.6 on 2025-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per night')),
                ('beds', models.PositiveIntegerField(verbose_name='Number of beds')),
                ('baths', models.PositiveIntegerField(verbose_name='Number of baths')),
                ('wifi_available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('image', models.FileField(upload_to='rooms/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
