# Generated by Django 5.1.6 on 2025-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enochApp', '0002_contact_alter_apartment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Profile Picture')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
